server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

spring:
  application:
    name: gatewayservice
  cloud:
    gateway:
      routes:
        - id: resourceService
          uri: lb://RESOURCESERVICE
          predicates:
            - Path=/resources/**
        - id: songService
          uri: lb://SONGSERVICE
          predicates:
            - Path=/songs/**
        - id: eurekaServer
          uri: lb://EUREKASERVER
          predicates:
            - Path=/eureka/**
        - id: rabbit
          uri: ${RABBIT_HOST:http://localhost:15672}
          predicates:
            - Path=/rabbit/**
          filters:
            - RewritePath=/rabbit/(?<segment>.*),/$\{segment}
        - id: s3ninja
          uri: ${S3NINJA_HOST:http://localhost:9444}
          predicates:
            - Path=/s3/**
          filters:
            - RewritePath=/s3/(?<segment>.*),/$\{segment}