server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE

spring:
  application:
    name: gatewayservice
  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
      routes:
        - id: resourceService
          uri: lb://RESOURCESERVICE
          predicates:
            - Path=/resources/**
        - id: songService
          uri: lb://SONGSERVICE
          predicates:
            - Path=/songs/**
        - id: storageService
          uri: lb://STORAGESERVICE
          predicates:
            - Path=/storages/**
        - id: eurekaServer
          uri: lb://EUREKASERVER
          predicates:
            - Path=/eureka/**