version: "3.9"

services:
  resource-processor:
    image: ms/resource-processor
    restart: always
    build: ./resource-processor
    depends_on:
      - rabbitmq
      - resource-service
      - song-service
      - eureka
    environment:
      RABBIT_HOST: rabbitmq
      EUREKA_SERVICE_URL: 'http://eureka:8761'
      GATEWAY_URL: 'http://spring-cloud-gateway:8083'
    logging:
      driver: "elastic/elastic-logging-plugin:7.10.0"
      options:
        hosts: "http://localhost:9200"

  resource-service:
    image: ms/resource-service
    restart: always
    build: ./resource-service
    depends_on:
      - rabbitmq
      - s3-ninja
      - eureka
    environment:
      RABBIT_HOST: rabbitmq
      AWS_S3_ENDPOINT_URL: 'http://s3-ninja:9000'
      EUREKA_SERVICE_URL: 'http://eureka:8761'
      GATEWAY_URL: 'http://spring-cloud-gateway:8083'
    logging:
      driver: "elastic/elastic-logging-plugin:7.10.0"
      options:
        hosts: "http://localhost:9200"

  song-service:
    image: ms/song-service
    restart: always
    build: ./song-service
    depends_on:
      - eureka
    environment:
      EUREKA_SERVICE_URL: 'http://eureka:8761'
    logging:
      driver: "elastic/elastic-logging-plugin:7.10.0"
      options:
        hosts: "http://localhost:9200"

  storage-service:
    image: ms/storage-service
    restart: always
    build: ./storage-service
    depends_on:
      - eureka
    environment:
      EUREKA_SERVICE_URL: 'http://eureka:8761'
    logging:
      driver: "elastic/elastic-logging-plugin:7.10.0"
      options:
        hosts: "http://localhost:9200"

  rabbitmq:
    image: 'rabbitmq:3.8.9-management'
    ports:
      - "5672:5672"
      - "15672:15672"

  s3-ninja:
    image: 'scireum/s3-ninja:latest'
    ports:
      - "9444:9000"

  eureka:
    image: ms/eureka-server
    build: ./eureka-server
    ports:
      - "8761:8761"

  spring-cloud-gateway:
    image: ms/spring-gateway
    build: ./spring-cloud-gateway
    ports:
      - "8083:8083"
    environment:
      EUREKA_SERVICE_URL: 'http://eureka:8761'
      S3NINJA_HOST: 'http://s3-ninja:9000'
      RABBIT_HOST: 'http://rabbitmq:15672'
    logging:
      driver: "elastic/elastic-logging-plugin:7.10.0"
      options:
        hosts: "http://localhost:9200"

  elasticsearch:
    image: elasticsearch:8.1.3
    environment:
      discovery.type: 'single-node'
      xpack.security.enabled: 'false'
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      bootstrap.memory_lock: 'true'
      ELASTIC_PASSWORD: 'changeme'
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: kibana:8.1.3
    environment:
      ELASTICSEARCH_HOSTS: 'http://elasticsearch:9200'
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - '9000:8080'
    environment:
      KEYCLOAK_ADMIN: 'admin'
      KEYCLOAK_ADMIN_PASSWORD: 'admin'
    command:
      - start-dev

volumes:
  elasticsearch-data:
    driver: local