service1:
  name: resourceservice

service2:
  name: songservice

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

#RabbitMQ properties
spring:
  application:
    name: "resourceprocessor"
  rabbitmq:
    host: ${RABBIT_HOST:localhost}