service1:
  base:
    url: http://${RES_SERV_HOST:localhost}:8081/resources/
  name: resource-service

service2:
  base:
    url: http://${SONG_SERV_HOST:localhost}:8082/songs/
  name: song-service

#RabbitMQ properties
spring:
  rabbitmq:
    host: ${RABBIT_HOST:localhost}