#Application properties
server:
  port: 8082
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: "songservice"

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/