INSERT INTO STORAGE(BUCKET, PATH, STORAGE_TYPE) VALUES('tests3bucket', '/tempfiles', 'STAGING');
INSERT INTO STORAGE(BUCKET, STORAGE_TYPE) VALUES('tests3bucket', 'STAGING');
INSERT INTO STORAGE(BUCKET, STORAGE_TYPE) VALUES('prods3bucket', 'PERMANENT');
