#Application properties
server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

#Circuit Breaker
resilience4j.circuitbreaker:
  instances:
    backendA:
      slidingWindowSize: 100
      permittedNumberOfCallsInHalfOpenState: 10
      waitDurationInOpenState: 10000
      failureRateThreshold: 60
      eventConsumerBufferSize: 10
      registerHealthIndicator: true

#AWS properties
cloud:
  aws:
    region:
      static: ap-south-1
    stack:
      auto: false
    credentials:
      accessKey: AKIAIOSFODNN7EXAMPLE
      secretKey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    endpoint:
      uri: ${AWS_S3_ENDPOINT_URL:http://localhost:9444}
    s3:
      bucket: testmp3bucket

#RabbitMQ properties
spring:
  main:
    allow-circular-references: true
  application:
    name: "resourceservice"
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    template:
      retry:
        enabled: true
        initial-interval: 3s
        max-attempts: 6
        max-interval: 10s
        multiplier: 2

#Keycloak
keycloak:
  auth-server-url: http://localhost:9000
  realm: ms
  resource: oauth-server
  ssl-required: external
  use-resource-role-mappings: true
  autodetect-bearer-only: true
  credentials:
    secret: N7eYRvxgRCyIi5f548drL92QXqgoVaBl

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

storageservice:
  name: ${STORAGE_SERVICE_NAME:storageservice}

gateway:
  url: ${GATEWAY_URL:http://localhost:8083/}